### ISSUE TITLE
[Question] Deploying the app in production

### ISSUE THREAD

**Issue by lakshmantgld** [brotzky/code-splitting-react-webpack#6]
This is not an issue with the repo. I am just asking my question. BTW, awesome repo man. A very good getting started guide to code-splitting.

**1)** I deploy my react app to AWS S3. It is comfortable for hosting the static website. In case of code-splitting app, how do we deploy it in production ?

So my directory structure for a basic react app without any code-splitting looks like this:

```
- index.html
- app.bundle.js
- app.css
```

I am just confused about the directory structure of code-splitting app in production.

**2)**  What is the difference between **commonChunkPlugin** and **vendor**. I understand that **vendor**  removes the code from **app.js** and contains the common modules, but I dont understand the relation between **commonChunkPlugin** and **vendor**.

**3) Benefits of using vendor.js:**

1. We will be updating our app.js time to time, but updating vendor.js is rare (compared to app, vendor updation is rare). We separate it so that the vendor maintains the same hash and app's hash changes so that the browser pulls the new app again, but not the vendor. Thus, reducing the payload and utilizing the cache performance. Is this the benefit or are they any other benefits too ?

If you feel this issue is not related to repo, please feel free to close the issue.

**Comment by brotzky** [comment]
**1)** I don't have any experience with AWS S3, to be honest. Since the build produces a bunch of static files it's not different than deploying any other static files.

Deploying
```
- index.html
- app.bundle.js
- app.css
```
and
```
- index.html
- app.bundle.js
- app.css
- 0.asdkfjas8j13.js
- 1.gaskdjga93r.js
...
```
is all the same.

**2)** **vendor.js** is useful for things that aren't really changing much -- this can be third party libraries such as React, moment, redux, numeral, lodash/underscore, etc. It's really up to you to decide. The principle is that it saves you from having to re-cache all those files every time you update your application. Your **app.js** code is probably evolving daily whereas your **vendor.js** code could be the same for many days/weeks/months.

**commonChunkPlugin** is probably best referred to through the documentation: https://webpack.js.org/plugins/commons-chunk-plugin/

vendor is just explicitly naming a chunk, whereas the rest are 0, 1, etc.

**3)** Yes, correct. I guess I sort of answered that in **2** :)
